apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: noel-ns
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8004
      targetPort: 8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: noel-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: flowforge/analytics-service:latest
          ports:
            - containerPort: 8004
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://postgres:postgres@postgres:5432/analytics_db
            - name: REDIS_URL
              value: redis://redis:6379
            - name: APP_PORT
              value: "8004"
            - name: STREAM_CONSUMER_GROUP
              value: analytics-group
            - name: STREAM_CONSUMER_NAME
              value: analytics-worker-1
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-service-hpa
  namespace: noel-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
