apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: noel-ns
spec:
  type: ClusterIP
  selector:
    app: task-service
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: noel-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: flowforge/task-service:latest
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              value: postgresql+asyncpg://postgres:postgres@postgres:5432/task_db
            - name: REDIS_URL
              value: redis://redis:6379
            - name: APP_PORT
              value: "8003"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: task-service-hpa
  namespace: noel-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task-service
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
