---
# Source: flowforge/charts/analysis-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flowforge-dev-analysis-service-active
  namespace: default
spec:
  selector:
    app: flowforge-dev-analysis-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
---
# Source: flowforge/charts/analysis-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flowforge-dev-analysis-service-preview
  namespace: default
spec:
  selector:
    app: flowforge-dev-analysis-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
---
# Source: flowforge/charts/analysis-service/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: default
spec:
  selector:
    app: flowforge-dev-analysis-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
