apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flowforge-dev-frontend
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flowforge-dev-frontend
  strategy:
    blueGreen:
      activeService: flowforge-dev-frontend-active
      previewService: flowforge-dev-frontend-preview
      autoPromotionEnabled: false
      previewReplicaCount: 1
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        tier: frontend
        app: flowforge-dev-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flowforge-dev-frontend
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: flowforge-dev-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: frontend
          image: "ghcr.io/noel-mathews-org/flowforge/frontend:a97a9b2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: flowforge-config
            - secretRef:
                name: flowforge-secret
          env:
            - name: APP_PORT
              value: "3000"
            - name: GATEWAY_PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
