apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flowforge-dev-project-service
  namespace: default
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: {}
  selector:
    matchLabels:
      app: flowforge-dev-project-service
  template:
    metadata:
      labels:
        tier: backend
        app: flowforge-dev-project-service
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - flowforge-dev-project-service
            topologyKey: "kubernetes.io/hostname"
      serviceAccountName: flowforge-dev-project-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: project-service
          image: "ghcr.io/noel-mathews-org/flowforge/project-service:a97a9b2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: flowforge-config
            - secretRef:
                name: flowforge-secret
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flowforge-secret
                  key: DATABASE_PASSWORD
            - name: DATABASE_URL
              value: "postgresql+asyncpg://postgres:$(DB_PASSWORD)@postgres.dev.svc.cluster.local:5432/project_db"
            - name: REDIS_URL
              value: "redis://redis.dev.svc.cluster.local:6379"
            - name: APP_PORT
              value: "8002"
            - name: GATEWAY_PORT
              value: "8002"
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
