name: Auth Service CI

on:
  push:
    branches:
      - Cloud-Track-dev
    paths:
      - 'auth-service/**'

permissions:
  contents: write
  id-token: write

jobs:
  run-ci:
    uses: Noel-Mathews-Org/.github/.github/workflows/_ci-reusable.yml@main
    with:
      service_name: auth-service
      project_key: Flow_auth_service
    secrets: inherit

