name: Frontend CI

on:
  push:
    branches:
      - Cloud-Track-dev
    paths:
      - 'frontend/**'
      - 'Helm/values-common.yaml'
      - 'Helm/values-dev.yaml'

permissions:
  contents: write
  packages: write

jobs:
  run-ci:
    if: "!contains(github.event.head_commit.message, 'chore(gitops)')"
    uses: ./.github/workflows/_ci-reusable.yml
    with:
      service_name: frontend
      project_key: Flow_frontend
    secrets:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      DEVELOPMENT_TEAM_EMAIL: ${{ secrets.DEVELOPMENT_TEAM_EMAIL }}
      GH_PAT: ${{ secrets.GH_PAT }}
