name: Notification Worker CI

on:
  push:
    branches:
      - Cloud-Track-dev
    paths:
      - 'notification-worker/**'

permissions:
  contents: write
  id-token: write

jobs:
  run-ci:
    uses: Noel-Mathews-Org/.github/.github/workflows/_ci-reusable.yml@main
    with:
      service_name: notification-worker
      project_key: Flow_notification_worker
    secrets: inherit

