name: Project Service CI

on:
  push:
    branches:
      - flowforgev2
    paths:
      - 'project-service/**'

permissions:
  contents: write
  packages: write

jobs:
  run-ci:
    uses: ./.github/workflows/_ci-reusable.yml
    with:
      service_name: project-service
      project_key: Flow_project_service
    secrets:
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      DEVELOPMENT_TEAM_EMAIL: ${{ secrets.DEVELOPMENT_TEAM_EMAIL }}
      GH_PAT: ${{ secrets.GH_PAT }}
