name: Terraform PR Plan

# on:
#   pull_request:
#     branches:
#       - Cloud-Track-dev
#       - Cloud-Track-prod
#     paths:
#       - 'terraform/**'
on:
  workflow_dispatch:

jobs:
  terraform-plan:
    name: Generate Terraform Plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Determine Environment
        id: env-setter
        run: |
          if [[ "${{ github.base_ref }}" == "Cloud-Track-prod" ]]; then
            echo "WORKING_DIR=terraform/env/prod" >> $GITHUB_OUTPUT
            echo "ENV_NAME=PROD" >> $GITHUB_OUTPUT
          else
            echo "WORKING_DIR=terraform/env/dev" >> $GITHUB_OUTPUT
            echo "ENV_NAME=DEV" >> $GITHUB_OUTPUT
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ${{ steps.env-setter.outputs.WORKING_DIR }}
        run: terraform init

      - name: Terraform Validate
        working-directory: ${{ steps.env-setter.outputs.WORKING_DIR }}
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ steps.env-setter.outputs.WORKING_DIR }}
        run: |
          terraform plan -no-color -out=tfplan > plan_output.txt
          
          # We need to escape the output to properly safely inject it into the GitHub script comment later
          PLAN=$(cat plan_output.txt)
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "plan<<$EOF" >> $GITHUB_OUTPUT
          echo "$PLAN" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Comment PR with Plan
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.plan }}"
          ENV_NAME: "${{ steps.env-setter.outputs.ENV_NAME }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Plan for \`${process.env.ENV_NAME}\` 🏗️
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
